# Site settings
title: "cnx has spoken"
bye_message: "Thx!"
baseurl: "/cnx/"
url: "https://lynfs.github.io"
disqus: cnx

# Header settings
nick: "cnx"
mail:
    domain: "protonmail"
    ext: "ch"
source_code:
    server: "github.com"
    nick: "cnx"
blog:
    server: "wordpress.com"
    nick: "cnx"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
